att11

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,7 +20,7 @@ jobs:
         ports:
           - 5432:5432
         options: >-
-          --health-cmd pg_isready
+          --health-cmd "pg_isready -U postgresql -d moviesdb"
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5
@@ -59,5 +59,13 @@ jobs:
       - name: Healthcheck
         run: |
           echo "Waiting for app to start..."
-          sleep 60
-          curl -f https://movieservice-production-dd97.up.railway.app/actuator/health | grep "UP"
+                    for i in {1..10}; do
+                      if curl -s -f https://movieservice-production-dd97.up.railway.app/actuator/health | grep "UP"; then
+                        echo "App is UP!"
+                        exit 0
+                      fi
+                      echo "Retry $i: App is not ready yet..."
+                      sleep 10
+                    done
+                    echo "App failed to start in time"
+                    exit 1
